### ISSUE TITLE
Emphasize ARRAY type uses one-based numbering

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave-docs#113]
See https://www.postgresql.org/docs/current/arrays.html

> By default PostgreSQL uses a one-based numbering convention for arrays, that is, an array of n elements starts with array[1] and ends with array[n].

Relevant RW doc page: https://docs.risingwave.com/sql/data-types/array-type#array-type

**Comment by stdrc** [comment]
Fixed by #119
