### ISSUE TITLE
miss sources in page `ingestion/supported-sources-and-formats#supported-sources`

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave-docs#80]
thanks @neverchanje found that
https://docs.risingwave.com/ingestion/supported-sources-and-formats#supported-sources such as mqtt and iceberg

**Comment by neverchanje** [comment]
Thanks for creating this issue.
Specifically, missing sources include:
- Azure Blob
- Iceberg
- MQTT
- NATS JetStream
- Load Generator (not sure if we want to list it)

Furthermore, you may consider adding doc links about ingesting from vendor-hosted systems to the list, for example:
- MQTT vendors: 
  - https://docs.risingwave.com/integrations/sources/solace
  - https://docs.risingwave.com/integrations/sources/coreflux-broker
  - https://docs.risingwave.com/integrations/sources/emqx
  - https://docs.risingwave.com/integrations/sources/hivemq
- Postgres vendors:
  - Neon
  - Supabase
- a bunch of Kafka vendors.
